import { addDaysIso, generateClasses, localIsoDate } from "./edu";
import type { DemoClass, DemoCourse, DemoRoom, DemoStudent, DemoTeacher } from "./types";

export { formatViDate, localIsoDate, demoNow, DEMO_AS_OF_ISO } from "./edu";

export const DEMO_TEACHERS: DemoTeacher[] = [
  { id: "mai", name: "Mai Trần", specialty: "Hip-hop / Jazz / Waacking" },
  { id: "ha", name: "Hà Nguyễn", specialty: "Contemporary / Heels" },
  { id: "linh", name: "Linh Phạm", specialty: "Ballet / Kids" },
  { id: "khoa", name: "Khoa Võ", specialty: "Hip-hop / Freestyle" },
  { id: "thu", name: "Thu Anh", specialty: "Ballet / Stretch" },
  { id: "nam", name: "Nam Lê", specialty: "House / Locking" },
  { id: "vy", name: "Vy Đặng", specialty: "K-pop / Jazz" },
  { id: "quan", name: "Quân Hồ", specialty: "Hip-hop / Battle" },
  { id: "nga", name: "Nga Bùi", specialty: "Contemporary / Impro" },
  { id: "phuc", name: "Phúc Trần", specialty: "Breaking / Power" },
  { id: "han", name: "Hân Võ", specialty: "Heels / Commercial" },
  { id: "duc", name: "Đức Phạm", specialty: "Open practice / Freestyle" },
  { id: "tram", name: "Trâm Nguyễn", specialty: "Kids / Ballet" },
  { id: "son", name: "Sơn Đỗ", specialty: "Popping / Waacking" },
];

export const DEMO_ROOMS: DemoRoom[] = [
  { id: "p1", label: "Studio 1", branchId: "br-q1", active: true, note: "Gương full · loa" },
  { id: "p2", label: "Studio 2", branchId: "br-q1", active: true, note: "Heels / Jazz" },
  { id: "ga", label: "Floor A", branchId: "br-q1", active: true, note: "Sàn gỗ · Ballet" },
  { id: "p6", label: "Studio B", branchId: "br-q1", active: true, note: "K-pop / Freestyle" },
  { id: "p7", label: "Studio C", branchId: "br-q1", active: true, note: "Nhỏ · private" },
  { id: "p3", label: "Studio 3", branchId: "br-td", active: true, note: "Ưu tiên Contemporary" },
  { id: "gb", label: "Kids Room", branchId: "br-td", active: true, note: "Nhỏ · mats" },
  { id: "p8", label: "Studio TD-2", branchId: "br-td", active: true, note: "Gương · LED" },
  { id: "p9", label: "Open Floor TD", branchId: "br-td", active: false, note: "Bảo trì sàn" },
  { id: "p4", label: "Studio 1", branchId: "br-tdc", active: true, note: "Chi nhánh Thủ Đức" },
  { id: "p5", label: "Studio Open", branchId: "br-tdc", active: true, note: "Open practice" },
  { id: "p10", label: "Studio TĐC-2", branchId: "br-tdc", active: true, note: "Jazz / House" },
];

export const DEMO_STUDENTS: DemoStudent[] = [
  { id: "st-1", name: "Lan Nguyễn", phone: "0901 234 001" },
  { id: "st-2", name: "Hương Trần", phone: "0901 234 002" },
  { id: "st-3", name: "Minh Lê", phone: "0901 234 003" },
  { id: "st-4", name: "An Phạm", phone: "0901 234 004" },
  { id: "st-5", name: "Ngọc Võ", phone: "0901 234 005" },
  { id: "st-6", name: "Tuấn Hoàng", phone: "0901 234 006" },
  { id: "st-7", name: "My Đặng", phone: "0901 234 007" },
  { id: "st-8", name: "Khoa Bùi", phone: "0901 234 008" },
  { id: "st-9", name: "Trang Lý", phone: "0901 234 009" },
  { id: "st-10", name: "Phúc Huỳnh", phone: "0901 234 010" },
  { id: "st-11", name: "Hà Phan", phone: "0901 234 011" },
  { id: "st-12", name: "Duy Vũ", phone: "0901 234 012" },
  { id: "st-13", name: "Yến Mai", phone: "0901 234 013" },
  { id: "st-14", name: "Long Đỗ", phone: "0901 234 014" },
  { id: "st-15", name: "Quỳnh Tô", phone: "0901 234 015" },
  { id: "st-16", name: "Nam Cao", phone: "0901 234 016" },
  { id: "st-17", name: "Bích Ngọc", phone: "0901 234 017" },
  { id: "st-18", name: "Hoàng Sơn", phone: "0901 234 018" },
  { id: "st-19", name: "Mai Chi", phone: "0901 234 019" },
  { id: "st-20", name: "Đức Anh", phone: "0901 234 020" },
  { id: "st-21", name: "Thanh Tú", phone: "0901 234 021" },
  { id: "st-22", name: "Kim Ngân", phone: "0901 234 022" },
  { id: "st-23", name: "Bảo Trâm", phone: "0901 234 023" },
  { id: "st-24", name: "Nhật Hà", phone: "0901 234 024" },
  { id: "st-25", name: "Việt Anh", phone: "0901 234 025" },
  { id: "st-26", name: "Thuỳ Linh", phone: "0901 234 026" },
  { id: "st-27", name: "Quang Huy", phone: "0901 234 027" },
  { id: "st-28", name: "Diễm My", phone: "0901 234 028" },
  { id: "st-29", name: "Khánh Vy", phone: "0901 234 029" },
  { id: "st-30", name: "Sơn Tạ", phone: "0901 234 030" },
  { id: "st-k1", name: "An Nhi", phone: "0901 888 001" },
  { id: "st-k2", name: "Minh Khang", phone: "0901 888 002" },
  { id: "st-k3", name: "Bảo Châu", phone: "0901 888 003" },
  { id: "st-k4", name: "Gia Hân", phone: "0901 888 004" },
  { id: "st-k5", name: "Tuệ Lâm", phone: "0901 888 005" },
  { id: "st-k6", name: "Ngọc Hà", phone: "0901 888 006" },
  /** Chưa ghi danh — để demo filter Học viên */
  { id: "st-new1", name: "Uyên Nhi", phone: "0901 777 001" },
  { id: "st-new2", name: "Khải Minh", phone: "0901 777 002" },
  { id: "st-new3", name: "Phương Anh", phone: "0901 777 003" },
];

export const DEFAULT_STUDENT = DEMO_STUDENTS[1];

/**
 * Seed canvas — đồng hồ demo 24/08/2026 17:15 VN.
 * Heels đang diễn ra 17:00; Hip-hop chưa diễn ra 19:00.
 * Long (st-14) chưa trong Hip-hop — chat “Thêm Long vào Hip-hop”.
 */
export const DEMO_COURSES: DemoCourse[] = [
  {
    id: "crs-hiphop",
    name: "Hip-hop Open",
    level: "Open",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-15",
    teacherIds: ["mai", "khoa"],
    roomId: "p1",
    capacity: 16,
    studentIds: [
      "st-1",
      "st-2",
      "st-3",
      "st-4",
      "st-5",
      "st-6",
      "st-7",
      "st-8",
      "st-9",
      "st-10",
      "st-11",
      "st-12",
      "st-15",
      "st-16",
      "st-17",
      "st-20",
    ],
    schedule: { weekdays: [1, 4], startTime: "19:00", endTime: "20:00", sessionCount: 10, firstDate: "2026-08-03" },
    note: "T2 · T5 tối · Mai + Khoa · Long chưa ghi danh",
  },
  {
    id: "crs-contemp",
    name: "Contemporary",
    level: "Intermediate",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-10",
    teacherIds: ["ha"],
    roomId: "p3",
    capacity: 14,
    studentIds: ["st-2", "st-3", "st-7", "st-9", "st-11", "st-13", "st-18", "st-19", "st-21", "st-22", "st-26", "st-28"],
    schedule: { weekdays: [2, 5], startTime: "18:00", endTime: "19:30", sessionCount: 10, firstDate: "2026-08-04" },
    note: "T3 · T6 · Thảo Điền",
  },
  {
    id: "crs-ballet",
    name: "Ballet Beginner",
    level: "Beginner",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-20",
    teacherIds: ["linh", "thu"],
    roomId: "ga",
    capacity: 12,
    studentIds: ["st-1", "st-3", "st-9", "st-15", "st-17", "st-19", "st-22", "st-23", "st-24", "st-29"],
    schedule: { weekdays: [3], startTime: "17:00", endTime: "18:00", sessionCount: 8, firstDate: "2026-08-05" },
    note: "T4 chiều · Floor A",
  },
  {
    id: "crs-jazz",
    name: "Jazz Open",
    level: "Open",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-30",
    teacherIds: ["mai"],
    roomId: "p2",
    capacity: 16,
    studentIds: ["st-1", "st-5", "st-14", "st-6", "st-10", "st-18", "st-21", "st-25", "st-27", "st-30"],
    schedule: { weekdays: [6], startTime: "10:00", endTime: "11:30", sessionCount: 8, firstDate: "2026-08-08" },
    note: "Thứ Bảy sáng",
  },
  {
    id: "crs-kpop",
    name: "K-pop",
    level: "Open",
    enrollStart: "2026-08-10",
    enrollEnd: "2026-09-30",
    teacherIds: ["ha", "khoa"],
    roomId: "p1",
    capacity: 18,
    studentIds: [
      "st-2",
      "st-4",
      "st-7",
      "st-8",
      "st-15",
      "st-16",
      "st-17",
      "st-20",
      "st-22",
      "st-23",
      "st-26",
      "st-28",
      "st-29",
    ],
    schedule: { weekdays: [6], startTime: "14:00", endTime: "15:30", sessionCount: 8, firstDate: "2026-08-15" },
    note: "T7 chiều",
  },
  {
    id: "crs-heels",
    name: "Heels",
    level: "Open",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-05",
    teacherIds: ["ha"],
    roomId: "p2",
    capacity: 12,
    studentIds: ["st-2", "st-7", "st-13", "st-9", "st-15", "st-19", "st-22", "st-24", "st-26", "st-28"],
    schedule: { weekdays: [1], startTime: "17:00", endTime: "18:30", sessionCount: 8, firstDate: "2026-08-03" },
    note: "T2 chiều · demo đang diễn ra 17:15",
  },
  {
    id: "crs-kids",
    name: "Kids 5–8",
    level: "5–8 tuổi",
    enrollStart: "2026-07-01",
    enrollEnd: "2026-08-10",
    teacherIds: ["linh"],
    roomId: "gb",
    capacity: 10,
    studentIds: ["st-k1", "st-k2", "st-k3", "st-k4", "st-k5", "st-k6"],
    schedule: { weekdays: [6], startTime: "09:00", endTime: "10:00", sessionCount: 8, firstDate: "2026-08-01" },
    note: "Đã đóng tuyển · Thảo Điền",
  },
  {
    id: "crs-waacking",
    name: "Waacking",
    level: "Open",
    enrollStart: "2026-08-20",
    enrollEnd: "2026-09-30",
    teacherIds: ["mai"],
    roomId: "p2",
    capacity: 12,
    studentIds: ["st-14", "st-8", "st-12", "st-16", "st-20", "st-25", "st-27", "st-30"],
    schedule: { weekdays: [3], startTime: "19:30", endTime: "20:30", sessionCount: 6, firstDate: "2026-08-26" },
    note: "T4 tối · đã sinh lớp từ 26/08",
  },
  {
    id: "crs-open-tdc",
    name: "Open Practice TD",
    level: "Open",
    enrollStart: "2026-08-15",
    enrollEnd: "2026-09-30",
    teacherIds: ["khoa"],
    roomId: "p5",
    capacity: 20,
    studentIds: ["st-6", "st-10", "st-12", "st-18", "st-25", "st-27", "st-30"],
    schedule: { weekdays: [1, 3], startTime: "20:30", endTime: "21:30", sessionCount: 6, firstDate: "2026-08-18" },
    note: "Thủ Đức · tối muộn",
  },
  /** Khóa filler — lấp bảng; sessionCount thấp/0 để không phình lớp */
  {
    id: "crs-hiphop-int",
    name: "Hip-hop Intermediate",
    level: "Intermediate",
    enrollStart: "2026-08-05",
    enrollEnd: "2026-09-20",
    teacherIds: ["mai", "khoa"],
    roomId: "p1",
    capacity: 14,
    studentIds: ["st-5", "st-8", "st-12", "st-16", "st-20", "st-25", "st-27", "st-30"],
    schedule: { weekdays: [2], startTime: "19:00", endTime: "20:30", sessionCount: 4, firstDate: "2026-08-11" },
    note: "T3 tối · filler",
  },
  {
    id: "crs-locking",
    name: "Locking Open",
    level: "Open",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-30",
    teacherIds: ["khoa"],
    roomId: "p4",
    capacity: 12,
    studentIds: ["st-6", "st-10", "st-18", "st-25", "st-27"],
    schedule: { weekdays: [4], startTime: "18:00", endTime: "19:00", sessionCount: 0, firstDate: "2026-08-06" },
    note: "Chưa sinh lớp",
  },
  {
    id: "crs-popping",
    name: "Popping",
    level: "Beginner",
    enrollStart: "2026-08-10",
    enrollEnd: "2026-09-25",
    teacherIds: ["khoa"],
    roomId: "p1",
    capacity: 12,
    studentIds: ["st-4", "st-12", "st-16", "st-30"],
    schedule: { weekdays: [5], startTime: "19:00", endTime: "20:00", sessionCount: 0, firstDate: "2026-08-14" },
    note: "Chưa sinh lớp",
  },
  {
    id: "crs-house",
    name: "House Groove",
    level: "Open",
    enrollStart: "2026-09-01",
    enrollEnd: "2026-10-15",
    teacherIds: ["mai"],
    roomId: "p2",
    capacity: 16,
    studentIds: [],
    schedule: { weekdays: [6], startTime: "16:00", endTime: "17:30", sessionCount: 0, firstDate: "2026-09-05" },
    note: "Nháp · mở tháng 9",
  },
  {
    id: "crs-vogue",
    name: "Vogue Femme",
    level: "Open",
    enrollStart: "2026-08-12",
    enrollEnd: "2026-09-30",
    teacherIds: ["mai"],
    roomId: "p2",
    capacity: 10,
    studentIds: ["st-7", "st-13", "st-19", "st-22", "st-26", "st-28"],
    schedule: { weekdays: [0], startTime: "15:00", endTime: "16:30", sessionCount: 2, firstDate: "2026-08-30" },
    note: "CN chiều",
  },
  {
    id: "crs-stretch",
    name: "Stretch & Flex",
    level: "Open",
    enrollStart: "2026-06-01",
    enrollEnd: "2026-07-31",
    teacherIds: ["thu"],
    roomId: "ga",
    capacity: 14,
    studentIds: ["st-1", "st-3", "st-9", "st-15", "st-17", "st-23", "st-24"],
    schedule: { weekdays: [3], startTime: "07:00", endTime: "08:00", sessionCount: 0, firstDate: "2026-06-03" },
    note: "Đã đóng · khóa hè",
  },
  {
    id: "crs-ballet-int",
    name: "Ballet Intermediate",
    level: "Intermediate",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-30",
    teacherIds: ["linh", "thu"],
    roomId: "ga",
    capacity: 12,
    studentIds: ["st-1", "st-9", "st-15", "st-17", "st-19", "st-23", "st-24", "st-29"],
    schedule: { weekdays: [1, 4], startTime: "18:30", endTime: "19:30", sessionCount: 4, firstDate: "2026-08-03" },
    note: "T2 · T5",
  },
  {
    id: "crs-pointe",
    name: "Pointe Prep",
    level: "Intermediate",
    enrollStart: "2026-09-05",
    enrollEnd: "2026-10-20",
    teacherIds: ["linh"],
    roomId: "ga",
    capacity: 8,
    studentIds: [],
    schedule: { weekdays: [2], startTime: "17:00", endTime: "18:00", sessionCount: 0, firstDate: "2026-09-08" },
    note: "Nháp · chờ đủ Beginner",
  },
  {
    id: "crs-jazz-funk",
    name: "Jazz Funk",
    level: "Open",
    enrollStart: "2026-08-08",
    enrollEnd: "2026-09-28",
    teacherIds: ["mai"],
    roomId: "p2",
    capacity: 14,
    studentIds: ["st-5", "st-6", "st-10", "st-14", "st-18", "st-21"],
    schedule: { weekdays: [5], startTime: "18:00", endTime: "19:00", sessionCount: 0, firstDate: "2026-08-14" },
    note: "Chưa sinh lớp",
  },
  {
    id: "crs-kpop-beg",
    name: "K-pop Beginner",
    level: "Beginner",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-15",
    teacherIds: ["ha"],
    roomId: "p3",
    capacity: 16,
    studentIds: ["st-4", "st-8", "st-11", "st-20", "st-21", "st-23", "st-26", "st-28", "st-29"],
    schedule: { weekdays: [0], startTime: "10:00", endTime: "11:30", sessionCount: 4, firstDate: "2026-08-09" },
    note: "CN sáng",
  },
  {
    id: "crs-heels-int",
    name: "Heels Intermediate",
    level: "Intermediate",
    enrollStart: "2026-06-15",
    enrollEnd: "2026-08-01",
    teacherIds: ["ha"],
    roomId: "p2",
    capacity: 10,
    studentIds: ["st-2", "st-7", "st-13", "st-19", "st-22"],
    schedule: { weekdays: [4], startTime: "17:00", endTime: "18:30", sessionCount: 0, firstDate: "2026-06-18" },
    note: "Đã đóng · khoá trước",
  },
  {
    id: "crs-kids-9",
    name: "Kids 9–12",
    level: "9–12 tuổi",
    enrollStart: "2026-07-01",
    enrollEnd: "2026-08-15",
    teacherIds: ["linh"],
    roomId: "gb",
    capacity: 12,
    studentIds: ["st-k1", "st-k2", "st-k3", "st-k4"],
    schedule: { weekdays: [0], startTime: "09:00", endTime: "10:00", sessionCount: 0, firstDate: "2026-07-05" },
    note: "Đã đóng tuyển",
  },
  {
    id: "crs-choreo",
    name: "Choreography Lab",
    level: "Open",
    enrollStart: "2026-08-18",
    enrollEnd: "2026-10-01",
    teacherIds: ["khoa", "ha"],
    roomId: "p5",
    capacity: 16,
    studentIds: ["st-6", "st-10", "st-12", "st-14", "st-18", "st-25", "st-27", "st-30"],
    schedule: { weekdays: [6], startTime: "18:00", endTime: "20:00", sessionCount: 0, firstDate: "2026-08-29" },
    note: "Thủ Đức · lab",
  },
  {
    id: "crs-latin",
    name: "Latin Fusion",
    level: "Beginner",
    enrollStart: "2026-09-10",
    enrollEnd: "2026-10-30",
    teacherIds: ["thu"],
    roomId: "p3",
    capacity: 14,
    studentIds: [],
    schedule: { weekdays: [3], startTime: "19:00", endTime: "20:00", sessionCount: 0, firstDate: "2026-09-16" },
    note: "Nháp · tháng 9",
  },
  {
    id: "crs-break",
    name: "Breaking Basics",
    level: "Beginner",
    enrollStart: "2026-08-01",
    enrollEnd: "2026-09-20",
    teacherIds: ["khoa"],
    roomId: "p4",
    capacity: 12,
    studentIds: ["st-6", "st-12", "st-18", "st-25", "st-27", "st-30"],
    schedule: { weekdays: [2], startTime: "20:00", endTime: "21:00", sessionCount: 2, firstDate: "2026-08-25" },
    note: "T3 tối · Thủ Đức",
  },
];

function buildSeedClasses(): DemoClass[] {
  let all: DemoClass[] = [];
  for (const course of DEMO_COURSES) {
    all = generateClasses(course, all);
  }
  all = all.map((row) => (row.id === "cls-crs-jazz-2" ? { ...row, cancelled: true } : row));

  /** Lấp lịch hôm nay (24/08/2026 · T2) — rooms board mockup. */
  const todayFill: DemoClass[] = [
    {
      id: "cls-fill-ga-am",
      courseId: "crs-ballet",
      date: "2026-08-24",
      startTime: "09:00",
      endTime: "10:00",
      teacherId: "linh",
      roomId: "ga",
      capacity: 12,
      studentIds: ["st-1", "st-3", "st-9", "st-15", "st-17"],
      cancelled: false,
    },
    {
      id: "cls-fill-ga-pm",
      courseId: "crs-ballet",
      date: "2026-08-24",
      startTime: "18:30",
      endTime: "19:30",
      teacherId: "thu",
      roomId: "ga",
      capacity: 12,
      studentIds: ["st-19", "st-22", "st-23", "st-24"],
      cancelled: false,
    },
    {
      id: "cls-fill-p3-now",
      courseId: "crs-contemp",
      date: "2026-08-24",
      startTime: "16:30",
      endTime: "18:00",
      teacherId: "ha",
      roomId: "p3",
      capacity: 14,
      studentIds: ["st-2", "st-7", "st-11", "st-18", "st-21"],
      cancelled: false,
    },
    {
      id: "cls-fill-p3-eve",
      courseId: "crs-contemp",
      date: "2026-08-24",
      startTime: "19:00",
      endTime: "20:30",
      teacherId: "nga",
      roomId: "p3",
      capacity: 14,
      studentIds: ["st-3", "st-9", "st-13", "st-26"],
      cancelled: false,
    },
    {
      id: "cls-fill-gb-kids",
      courseId: "crs-kids",
      date: "2026-08-24",
      startTime: "16:00",
      endTime: "17:00",
      teacherId: "linh",
      roomId: "gb",
      capacity: 10,
      studentIds: ["st-k1", "st-k2", "st-k3"],
      cancelled: false,
    },
    {
      id: "cls-fill-gb-eve",
      courseId: "crs-kids",
      date: "2026-08-24",
      startTime: "18:00",
      endTime: "19:00",
      teacherId: "tram",
      roomId: "gb",
      capacity: 10,
      studentIds: ["st-k4", "st-k5", "st-k6"],
      cancelled: false,
    },
    {
      id: "cls-fill-p1-am",
      courseId: "crs-kpop",
      date: "2026-08-24",
      startTime: "10:30",
      endTime: "12:00",
      teacherId: "vy",
      roomId: "p1",
      capacity: 18,
      studentIds: ["st-2", "st-4", "st-8", "st-15"],
      cancelled: false,
    },
    {
      id: "cls-fill-p2-eve",
      courseId: "crs-heels",
      date: "2026-08-24",
      startTime: "19:30",
      endTime: "21:00",
      teacherId: "han",
      roomId: "p2",
      capacity: 12,
      studentIds: ["st-5", "st-7", "st-10", "st-16"],
      cancelled: false,
    },
    {
      id: "cls-fill-p4-now",
      courseId: "crs-jazz",
      date: "2026-08-24",
      startTime: "17:00",
      endTime: "18:00",
      teacherId: "nam",
      roomId: "p4",
      capacity: 14,
      studentIds: ["st-6", "st-10", "st-18", "st-25"],
      cancelled: false,
    },
    {
      id: "cls-fill-p4-eve",
      courseId: "crs-hiphop",
      date: "2026-08-24",
      startTime: "19:00",
      endTime: "20:00",
      teacherId: "quan",
      roomId: "p4",
      capacity: 16,
      studentIds: ["st-1", "st-11", "st-12", "st-20"],
      cancelled: false,
    },
    {
      id: "cls-fill-p5-mid",
      courseId: "crs-open-tdc",
      date: "2026-08-24",
      startTime: "15:00",
      endTime: "16:30",
      teacherId: "duc",
      roomId: "p5",
      capacity: 20,
      studentIds: ["st-14", "st-27", "st-30"],
      cancelled: false,
    },
    {
      id: "cls-fill-p6-now",
      courseId: "crs-kpop",
      date: "2026-08-24",
      startTime: "17:00",
      endTime: "18:30",
      teacherId: "vy",
      roomId: "p6",
      capacity: 16,
      studentIds: ["st-4", "st-8", "st-16", "st-28"],
      cancelled: false,
    },
    {
      id: "cls-fill-p6-eve",
      courseId: "crs-hiphop",
      date: "2026-08-24",
      startTime: "19:30",
      endTime: "20:30",
      teacherId: "quan",
      roomId: "p6",
      capacity: 16,
      studentIds: ["st-5", "st-9", "st-17"],
      cancelled: false,
    },
    {
      id: "cls-fill-p7-soon",
      courseId: "crs-jazz",
      date: "2026-08-24",
      startTime: "18:00",
      endTime: "19:00",
      teacherId: "phuc",
      roomId: "p7",
      capacity: 10,
      studentIds: ["st-21", "st-25"],
      cancelled: false,
    },
    {
      id: "cls-fill-p8-busy",
      courseId: "crs-contemp",
      date: "2026-08-24",
      startTime: "16:45",
      endTime: "18:15",
      teacherId: "nga",
      roomId: "p8",
      capacity: 14,
      studentIds: ["st-13", "st-19", "st-22", "st-26"],
      cancelled: false,
    },
    {
      id: "cls-fill-p8-eve",
      courseId: "crs-waacking",
      date: "2026-08-24",
      startTime: "19:00",
      endTime: "20:00",
      teacherId: "son",
      roomId: "p8",
      capacity: 12,
      studentIds: ["st-7", "st-15", "st-23"],
      cancelled: false,
    },
    {
      id: "cls-fill-p10-am",
      courseId: "crs-jazz",
      date: "2026-08-24",
      startTime: "11:00",
      endTime: "12:30",
      teacherId: "nam",
      roomId: "p10",
      capacity: 14,
      studentIds: ["st-6", "st-18", "st-27"],
      cancelled: false,
    },
    {
      id: "cls-fill-p10-eve",
      courseId: "crs-open-tdc",
      date: "2026-08-24",
      startTime: "18:30",
      endTime: "20:00",
      teacherId: "duc",
      roomId: "p10",
      capacity: 16,
      studentIds: ["st-14", "st-20", "st-30"],
      cancelled: false,
    },
  ];

  return [...all, ...todayFill];
}

export const DEMO_CLASSES: DemoClass[] = buildSeedClasses();

export function cloneSeedCourses(): DemoCourse[] {
  return DEMO_COURSES.map((c) => ({
    ...c,
    teacherIds: [...c.teacherIds],
    studentIds: [...c.studentIds],
    schedule: { ...c.schedule, weekdays: [...c.schedule.weekdays] },
  }));
}

export function cloneSeedClasses(): DemoClass[] {
  return DEMO_CLASSES.map((row) => ({ ...row, studentIds: [...row.studentIds] }));
}

export function cloneSeedRooms(): DemoRoom[] {
  return DEMO_ROOMS.map((r) => ({ ...r }));
}

export function studentByName(name: string): DemoStudent {
  const hit = DEMO_STUDENTS.find((s) => s.name === name || s.name.includes(name));
  return hit ?? DEFAULT_STUDENT;
}

export function findStudentFromIntent(text: string): DemoStudent {
  const t = text.normalize("NFC").toLowerCase();
  if (/hương/.test(t)) return studentByName("Hương Trần");
  if (/long/.test(t)) return studentByName("Long Đỗ");
  if (/\blan\b/.test(t)) return studentByName("Lan Nguyễn");
  if (/minh/.test(t)) return studentByName("Minh Lê");
  if (/\ban\b/.test(t)) return studentByName("An Phạm");
  if (/uyên/.test(t)) return studentByName("Uyên Nhi");
  return DEFAULT_STUDENT;
}

export function findCourseFromIntent(text: string, courses: DemoCourse[] = DEMO_COURSES): DemoCourse | undefined {
  const t = text.normalize("NFC").toLowerCase();
  const hit = courses.find((c) => t.includes(c.name.toLowerCase()) || t.includes(c.id.replace("crs-", "")));
  if (hit) return hit;
  if (/hip-?hop/.test(t)) return courses.find((c) => c.id === "crs-hiphop");
  if (/contemporary|đương đại/.test(t)) return courses.find((c) => c.id === "crs-contemp");
  if (/ballet/.test(t)) return courses.find((c) => c.id === "crs-ballet");
  if (/jazz/.test(t)) return courses.find((c) => c.id === "crs-jazz");
  if (/k-?pop/.test(t)) return courses.find((c) => c.id === "crs-kpop");
  if (/heels/.test(t)) return courses.find((c) => c.id === "crs-heels");
  if (/waacking/.test(t)) return courses.find((c) => c.id === "crs-waacking");
  if (/kids|nhí/.test(t)) return courses.find((c) => c.id === "crs-kids");
  if (/open practice|thủ đức|tdc/.test(t)) return courses.find((c) => c.id === "crs-open-tdc");
  return courses[0];
}

export function blankCourse(): DemoCourse {
  const today = localIsoDate();
  return {
    id: "",
    name: "",
    level: "Open",
    enrollStart: today,
    enrollEnd: addDaysIso(today, 30),
    teacherIds: ["mai"],
    roomId: "p1",
    capacity: 16,
    studentIds: [],
    schedule: {
      weekdays: [1],
      startTime: "18:00",
      endTime: "19:00",
      sessionCount: 8,
      firstDate: today,
    },
  };
}

export type BookingOption = { id: string; label: string };

export const BOOKING_SOURCES: BookingOption[] = [
  { id: "walkin", label: "Walk-in" },
  { id: "zalo", label: "Zalo" },
  { id: "web", label: "Web form" },
];

export const BOOKING_DURATIONS: BookingOption[] = [
  { id: "60", label: "60 phút" },
  { id: "90", label: "90 phút" },
];

export const DEMO_CUSTOMERS = DEMO_STUDENTS;
