/** Demo vault — Dolphin Racing (brand minh họa; địa chỉ TPHCM; ảnh/giá/SĐT placeholder). */

export const dolphinRacingBrand = "Dolphin Racing";

const unsplash = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const img = {
  hero: unsplash("photo-1558980664-1db506751c6c", 2000),
  night: unsplash("photo-1609630875171-b1321377ee65", 1800),
  wheel: unsplash("photo-1547447134-cd3f5c716030"),
  disc: unsplash("photo-1615172282427-9a57ef2d142e"),
  garage: unsplash("photo-1486262715619-67b85e0b08d3"),
  street: unsplash("photo-1558981806-ec527fa84c39"),
  sport: unsplash("photo-1558980394-4c7c9299fe96"),
  close: unsplash("photo-1591637333184-19aa84b3e01f"),
  carbon: unsplash("photo-1619767886558-efdc259cde1a"),
  hands: unsplash("photo-1487754180451-c456f719a1fc"),
  chrome: unsplash("photo-1558981359-219d6364c9c8"),
  pit: unsplash("photo-1532298229144-0ec0c57515c7"),
} as const;

export const dolphinRacingCopy = {
  metaTitle: "Dolphin Racing — Demo | Dolphin Software",
  metaDescription:
    "Demo website đồ chơi xe máy TP.HCM: dàn áo, mâm, phuộc, tay thắng. Thiết kế bởi Dolphin Software — ảnh minh họa.",
  demoBadge: "Demo website bởi Dolphin Software",
  demoNote:
    "Brand minh họa Dolphin Racing. Địa chỉ: TPHCM, Vietnam. Ảnh, giá, SĐT, giờ là placeholder — không phải garage đang chạy.",
  vaultLabel: "Demo vault",
  brand: "DOLPHIN",
  brandSub: "RACING",
  nav: {
    builds: "Dàn áo",
    rack: "Đồ chơi",
    pit: "Quy trình",
    proof: "Khách",
    shop: "Tới shop",
    book: "Nhắn Zalo",
  },
  hero: {
    eyebrow: "TPHCM, Vietnam",
    title: "Dolphin",
    titleEm: "Racing",
    tagline: "Xe xong. Rồi mới nói giá.",
    support: "Sơn dàn áo · mâm · phuộc · tay thắng — tay ga Sài Gòn.",
    ctaPrimary: "Launch",
    ctaSecondary: "Xem dàn áo",
    rpmIdle: "IDLE",
    rpmRed: "REDLINE",
    footLeft: "TPHCM · Vietnam",
    footRight: "Kéo — tua máy",
    image: img.hero,
    alt: "Xe máy đêm dưới đèn đường — ảnh minh họa, không phải xe shop",
  },
  marquee:
    "MÂM  —  PHUỘC  —  TAY THẮNG  —  SƠN DÀN ÁO  —  HEO DẦU  —  REDLEO  —  SUPERFLY  —  NITRON  —  GH-RACING  —  PIRELLI  —  TPHCM  —  ",
  story: {
    eyebrow: "01 / Pit lane",
    title: "Garage đêm.",
    titleEm: "Xe phải nhìn đã.",
    lead: "Dân kiểng không vào web để đọc catalog. Họ muốn thấy dàn áo, nghe tay nghề, rồi mới hỏi giá. Garage TPHCM — làm tay ga.",
    stats: [
      { k: "City", v: "TPHCM, Vietnam" },
      { k: "Giờ", v: "Hẹn trước (demo)" },
      { k: "Zalo", v: "Nhắn từ form" },
    ],
  },
  builds: {
    eyebrow: "02 / Grid",
    title: "Dàn áo xuất xưởng",
    support: "Ảnh stock + grade màu — không phải xe trong garage.",
    hint: "Vuốt ngang · hover để tua",
    items: [
      {
        id: "shvn-hong-den",
        tone: "pink",
        bike: "SHVN",
        name: "Hồng đen trong khu vực của bạn",
        image: img.night,
        alt: "Xe đêm ánh hồng — ảnh minh họa dàn SHVN hồng đen",
      },
      {
        id: "stylo-den-xanh",
        tone: "teal",
        bike: "STYLO",
        name: "Hơi thở của thành phố biển",
        image: img.street,
        alt: "Xe tay ga tông đen xanh — ảnh minh họa Stylo",
      },
      {
        id: "lead-den-bong",
        tone: "chrome",
        bike: "LEAD",
        name: "Hàng hiệu không cần giới thiệu",
        image: img.chrome,
        alt: "Xe đen bóng — ảnh minh họa Lead",
      },
      {
        id: "shvn-den-bong",
        tone: "ink",
        bike: "SHVN",
        name: "Đen bóng cũng đáng yêu mà",
        image: img.sport,
        alt: "Xe đen bóng — ảnh minh họa SHVN",
      },
      {
        id: "lead-214-xanh",
        tone: "lime",
        bike: "LEAD 214",
        name: "Đống sắt cũ ngày hôm qua, niềm kiêu hãnh hôm nay",
        image: img.close,
        alt: "Xe tông xanh — ảnh minh họa Lead 214",
      },
      {
        id: "var-den-vang",
        tone: "gold",
        bike: "VARIO",
        name: "Dứt khoát hay phân vân",
        image: img.pit,
        alt: "Xe đen vàng — ảnh minh họa Vario",
      },
      {
        id: "vis-den-xanh",
        tone: "teal",
        bike: "VISION",
        name: "Góc phố quen, người bạn đồng hành mới",
        image: img.street,
        alt: "Xe Vision đen xanh phục dựng — ảnh minh họa",
      },
      {
        id: "fuled",
        tone: "ink",
        bike: "FULED",
        name: "Đơn giản. Một chất riêng.",
        image: img.carbon,
        alt: "Xe tối giản — ảnh minh họa FULED",
      },
    ],
  },
  rack: {
    eyebrow: "03 / Rack",
    title: "Đồ chơi trên kệ",
    support: "Giá minh họa trên demo — không phải bảng giá đang bán.",
    filters: [
      { id: "all", label: "Tất cả" },
      { id: "tay", label: "Tay thắng" },
      { id: "phuoc", label: "Phuộc" },
      { id: "heo", label: "Heo dầu" },
      { id: "khac", label: "Khác" },
    ],
    items: [
      {
        cat: "tay",
        name: "Tay thắng / tay côn Redleo V2 nhôm 6",
        price: "2.300.000₫",
        image: img.disc,
        alt: "Chi tiết phanh xe — ảnh minh họa tay thắng Redleo",
      },
      {
        cat: "tay",
        name: "Tay thắng / tay côn Redleo V1",
        price: "1.900.000₫",
        image: img.disc,
        alt: "Chi tiết phanh xe — ảnh minh họa Redleo V1",
      },
      {
        cat: "phuoc",
        name: "Phuộc Superfly SHVN lò xo thường",
        price: "4.100.000₫",
        image: img.wheel,
        alt: "Phuộc / dàn chân — ảnh minh họa Superfly SHVN",
      },
      {
        cat: "phuoc",
        name: "Phuộc Superfly lò xo crom",
        price: "2.450.000₫",
        image: img.chrome,
        alt: "Phuộc lò xo crom — ảnh minh họa Superfly",
      },
      {
        cat: "phuoc",
        name: "Phuộc Superfly lò xo thường",
        price: "2.350.000₫",
        image: img.wheel,
        alt: "Phuộc Superfly — ảnh minh họa",
      },
      {
        cat: "heo",
        name: "Heo dầu GH-Racing Warlock 2P",
        price: "3.000.000₫",
        image: img.carbon,
        alt: "Heo dầu — ảnh minh họa GH-Racing",
      },
      {
        cat: "khac",
        name: "Vỏ Pirelli Rosso 70/80-14",
        price: "1.400.000₫",
        note: "Vario / Click / AB / Vision",
        image: img.wheel,
        alt: "Vỏ xe — ảnh minh họa Pirelli Rosso",
      },
      {
        cat: "khac",
        name: "Nhớt Ipone 10W-40",
        price: "160.000₫",
        image: img.garage,
        alt: "Chai nhớt garage — ảnh minh họa Ipone",
      },
      {
        cat: "khac",
        name: "Bao tay Harris V2",
        price: "300.000₫",
        image: img.hands,
        alt: "Bao tay xe — ảnh minh họa Harris V2",
      },
    ],
  },
  pit: {
    eyebrow: "04 / Quy trình",
    title: "Vào pit. Ra xe.",
    steps: [
      {
        n: "01",
        title: "Mang xe hoặc ảnh",
        body: "Zalo trước. Nói dòng xe, món muốn độ, ngân sách nếu có.",
      },
      {
        n: "02",
        title: "Chọn dàn / kệ",
        body: "Sơn, mâm, phuộc, tay thắng — khớp xe, không nhồi SKU.",
      },
      {
        n: "03",
        title: "Lắp · sơn · cân",
        body: "Garage làm. Hẹn lấy. Không hứa ngày nếu chưa xem xe.",
      },
      {
        n: "04",
        title: "Xuất xưởng",
        body: "Xe ra đèn. Chụp. Về.",
      },
    ],
  },
  proof: {
    eyebrow: "05 / Grid khách",
    title: "Người đã độ",
    items: [
      {
        name: "Anh Lễ",
        job: "Gói độ full option cho SH350",
        quote: "Quá là ưng với tay nghề của shop, trách nhiệm và đúng hẹn.",
      },
      {
        name: "Khách Bình Dương",
        job: "Phuộc",
        quote:
          "Mình từ Bình Dương, thấy shop uy tín vẫn cũng phải qua thay cho bằng được cái phuộc mình cần. Shop thoáng, chăm sóc nhiệt tình.",
      },
      {
        name: "Khách TP.HCM",
        job: "Đổi mâm xe",
        quote: "Mâm đẹp, thấy cửa hàng nhiệt tình, chu đáo.",
      },
    ],
  },
  book: {
    eyebrow: "06 / Radio",
    title: "Nhắn pit",
    titleEm: "trước khi tới.",
    support:
      "Form chỉ minh họa trên demo — không gửi tin nhắn thật. Zalo/SĐT: TODO.",
    fields: {
      name: "Tên",
      phone: "Zalo / SĐT",
      bike: "Dòng xe",
      need: "Cần gì",
      note: "Ghi chú",
    },
    bikes: ["SH", "Vario / Click", "Air Blade", "Vision", "Lead", "Stylo", "Khác"],
    needs: ["Sơn dàn áo", "Mâm", "Phuộc", "Tay thắng / heo", "Combo", "Chưa rõ"],
    cta: "Gửi (demo)",
    doneTitle: "Đã nhận trên demo.",
    doneBody: "Đây không phải tin nhắn tới shop. Zalo/SĐT: TODO.",
    doneAgain: "Gửi lại",
    zaloCta: "Mở Zalo",
    callCta: "Gọi shop",
  },
  shop: {
    eyebrow: "07 / Tọa độ",
    title: "TPHCM,",
    titleEm: "Vietnam",
    address: "TPHCM, Vietnam",
    hoursTitle: "Giờ",
    hours: "Hẹn trước (demo)",
    phoneLabel: "Điện thoại / Zalo",
    phone: "TODO",
    phoneTel: "",
    zaloHref: "#book",
    emailLabel: "Email",
    email: "TODO",
    fbLabel: "Facebook",
    fb: "TODO",
    fbHref: "#shop",
    mapLabel: "Mở bản đồ",
    mapHref:
      "https://www.google.com/maps/search/?api=1&query=Ho%20Chi%20Minh%20City%20Vietnam",
    image: img.garage,
    alt: "Không gian garage — ảnh minh họa, không phải mặt tiền shop",
  },
  faq: {
    eyebrow: "08 / FAQ",
    title: "Trước khi mang xe",
    items: [
      {
        q: "Có cần nhắn trước không?",
        a: "Nên nhắn trước. Giờ mở cửa trên demo là placeholder. Form không tới máy shop.",
      },
      {
        q: "Sơn dàn áo mất bao lâu?",
        a: "Shop báo khi xem xe / màu. Demo không ghi số ngày — không bịa lead time.",
      },
      {
        q: "Giá trên web có phải giá chốt?",
        a: "Giá trên demo là minh họa. Chốt khi xem xe.",
      },
      {
        q: "Nhận khách tỉnh không?",
        a: "Nhận khách tỉnh nếu hẹn trước. Review trên demo là placeholder.",
      },
    ],
  },
  final: {
    title: "Đèn đỏ.",
    titleEm: "Xe chưa xong.",
    support: "TPHCM. Mang xe. Chọn dàn. Ra phố.",
    ctaPrimary: "Nhắn Zalo",
    ctaSecondary: "Xem dàn áo",
    image: img.night,
  },
  disclaimer:
    "Demo pitch bởi Dolphin Software. Brand Dolphin Racing minh họa. Địa chỉ: TPHCM, Vietnam. Ảnh Unsplash, giá, SĐT, giờ, review là placeholder.",
  footer: {
    rights: "Dolphin Racing · demo",
    by: "Dolphin Software",
  },
  mobileBar: {
    map: "Map",
    zalo: "Zalo",
    call: "Gọi",
  },
} as const;
