/** Demo vault — Tam Thể F&B brand landing (tên quán thật; món/giờ/giá placeholder). */

export const tamTheDemoBrand = "Tam Thể";

const img = {
  heroDay: "/tam-the/hero-day.jpg",
  heroNight: "/tam-the/hero-night.jpg",
  coffee: "/tam-the/coffee.jpg",
  brunch: "/tam-the/brunch.jpg",
  pastry: "/tam-the/pastry.jpg",
  plate: "/tam-the/plate.jpg",
  cocktail: "/tam-the/cocktail.jpg",
  highball: "/tam-the/highball.jpg",
  interior: "/tam-the/interior.jpg",
  table: "/tam-the/table.jpg",
  bar: "/tam-the/bar.jpg",
  corner: "/tam-the/corner.jpg",
} as const;

export const tamTheDemoCopy = {
  metaTitle: "Tam Thể — Coffee · Brunch · Night | Demo Dolphin Software",
  metaDescription:
    "Demo website thương hiệu Tam Thể: cà phê, brunch và đêm cocktail tại Nguyễn Thị Minh Khai. Đặt bàn minh họa — không phải site chính thức.",
  demoBadge: "Demo website bởi Dolphin Software",
  demoNote:
    "Tên quán và địa chỉ theo đăng ký doanh nghiệp. Món, giờ, giá, ảnh không gian là placeholder — không phải menu hay giờ mở cửa thật.",
  siteLabel: "Dolphin Software",
  brand: "TAM THỂ",
  brandSub: "III",
  nav: {
    story: "Ba thể",
    day: "Ngày",
    night: "Đêm",
    space: "Không gian",
    visit: "Tới quán",
    book: "Đặt bàn",
  },
  mood: {
    day: "Ngày",
    night: "Đêm",
    label: "Chọn nhịp",
  },
  hero: {
    day: {
      eyebrow: "17/3 Nguyễn Thị Minh Khai",
      tagline: "Sáng chậm. Ly còn nóng.",
    },
    night: {
      eyebrow: "17/3 Nguyễn Thị Minh Khai",
      tagline: "Đèn thấp. Thành phố khép cửa.",
    },
    ctaPrimary: "Đặt bàn",
    ctaSecondary: "Ba thể",
    footLeft: "Quận 1 · Sài Gòn",
    footRight: "Kéo — chọn nhịp",
    dayImage: img.heroDay,
    dayAlt: "Ly cà phê sáng trên bàn gỗ — ảnh minh họa, không phải không gian Tam Thể",
    nightImage: img.heroNight,
    nightAlt: "Quầy bar đêm với ánh đèn ấm — ảnh minh họa, không phải không gian Tam Thể",
  },
  marquee: "Cà phê  —  Brunch  —  Cocktail  —  Nguyễn Thị Minh Khai  —  ",
  story: {
    eyebrow: "01 / Ba thể",
    title: "Một địa chỉ.",
    titleEm: "Ba nhịp.",
    lead: "Sáng là cà phê. Trưa là brunch. Đêm là cocktail. Cùng một tầng — chỉ đổi ánh sáng.",
    bodies: [
      {
        n: "I",
        title: "Cà phê",
        body: "Chỗ ngồi yên, ly đúng. Không cần catalog dài lúc 8 giờ sáng.",
        image: img.coffee,
        alt: "Ly cà phê trên quầy — ảnh minh họa",
      },
      {
        n: "II",
        title: "Brunch",
        body: "Bàn hai tới bốn người. Ảnh vài món — đủ để chọn quán, chưa cần gọi.",
        image: img.brunch,
        alt: "Bàn brunch — ảnh minh họa",
      },
      {
        n: "III",
        title: "Đêm",
        body: "Ly dài, nhóm nhỏ. Menu QR để lúc đã ngồi. Trang này kể mặt quán.",
        image: img.cocktail,
        alt: "Ly cocktail — ảnh minh họa",
      },
    ],
  },
  dayMenu: {
    eyebrow: "02 / Ngày",
    title: "Sáng tới chiều",
    support: "Signature minh họa — không phải thực đơn Tam Thể.",
    items: [
      {
        title: "Cold brew cam bergamot",
        note: "Cà phê",
        body: "Ủ chậm, vỏ cam. Ly sáng cho bàn làm việc.",
        image: img.coffee,
        alt: "Ly cà phê espresso — ảnh minh họa",
        featured: true,
      },
      {
        title: "Shakshuka trứng",
        note: "Brunch",
        body: "Sốt cà, trứng, bánh mì nướng.",
        image: img.brunch,
        alt: "Bàn brunch với trứng — ảnh minh họa",
        featured: false,
      },
      {
        title: "Granola sữa chua",
        note: "Sáng",
        body: "Yến mạch, hạt, mật ong.",
        image: img.pastry,
        alt: "Bánh pastry trên khay — ảnh minh họa",
        featured: false,
      },
      {
        title: "Bánh mì nhà",
        note: "Brunch",
        body: "Vỏ giòn, nhân theo ngày. TODO — món thật.",
        image: img.plate,
        alt: "Đĩa món fine-casual — ảnh minh họa",
        featured: false,
      },
    ],
  },
  nightMenu: {
    eyebrow: "03 / Đêm",
    title: "Khi đèn xuống",
    support: "Tên món placeholder.",
    items: [
      {
        title: "Negroni nhà",
        note: "01",
        body: "Đắng vừa, đá lớn, vỏ cam.",
        image: img.cocktail,
        alt: "Ly cocktail hổ phách — ảnh minh họa",
      },
      {
        title: "Highball yuzu",
        note: "02",
        body: "Soda, yuzu. Uống được lâu.",
        image: img.highball,
        alt: "Ly cocktail sáng — ảnh minh họa",
      },
      {
        title: "Đĩa chia sẻ",
        note: "03",
        body: "TODO — set thật của bếp.",
        image: img.plate,
        alt: "Món chia sẻ — ảnh minh họa",
      },
    ],
  },
  space: {
    eyebrow: "04 / Không gian",
    title: "Ánh sáng đổi.",
    titleEm: "Chỗ ngồi còn.",
    support: "Ảnh stock — thay ảnh quán khi có.",
    categories: [
      {
        id: "morning",
        label: "Sáng",
        caption: "Cửa sáng, bàn gỗ",
        image: img.interior,
        alt: "Nội thất quán cà phê — ảnh minh họa",
      },
      {
        id: "table",
        label: "Bàn",
        caption: "Hai tới bốn người",
        image: img.table,
        alt: "Bàn nhà hàng — ảnh minh họa",
      },
      {
        id: "bar",
        label: "Quầy",
        caption: "Đêm, đèn thấp",
        image: img.bar,
        alt: "Quầy bar — ảnh minh họa",
      },
      {
        id: "corner",
        label: "Góc",
        caption: "Chỗ ngồi yên",
        image: img.corner,
        alt: "Góc quán cạnh cửa sổ — ảnh minh họa",
      },
    ],
  },
  events: {
    eyebrow: "05 / Bàn riêng",
    title: "Nhóm nhỏ.",
    titleEm: "Không ồn hệ thống.",
    body: "Tiệc nhỏ / họp — chỉ hiện khi quán nhận. Demo để thấy chỗ kể.",
    cta: "Hỏi bàn riêng",
  },
  reserve: {
    eyebrow: "06 / Đặt bàn",
    title: "Giữ chỗ.",
    titleEm: "Rồi tới.",
    support: "Form demo — không gửi tới quán.",
    fields: {
      date: "Ngày",
      time: "Giờ",
      guests: "Số khách",
      mood: "Nhịp",
      name: "Tên",
      phone: "Điện thoại",
      note: "Ghi chú (dị ứng, sinh nhật…)",
    },
    moodOptions: ["Cà phê / brunch", "Đêm / cocktail", "Chưa chắc"],
    guestOptions: ["2", "3–4", "5–6", "7+"],
    times: ["09:00", "11:00", "13:00", "17:00", "19:00", "21:00"],
    cta: "Gửi giữ chỗ (demo)",
    doneTitle: "Đã ghi trên demo",
    doneBody: "Form không gửi đi. Site thật: Zalo / hộp thư quán.",
    doneAgain: "Gửi bàn khác",
  },
  visit: {
    eyebrow: "07 / Tới quán",
    title: "17/3",
    titleEm: "Nguyễn Thị Minh Khai",
    address: "Tầng 1, 17/3 Nguyễn Thị Minh Khai, Phường Sài Gòn, TP. Hồ Chí Minh",
    mapHref:
      "https://www.google.com/maps/search/?api=1&query=17%2F3+Nguyen+Thi+Minh+Khai%2C+Phuong+Sai+Gon%2C+Ho+Chi+Minh",
    mapLabel: "Mở Google Maps",
    hoursTitle: "Giờ mở cửa",
    hours: [
      { label: "Ngày", value: "TODO — giờ thật" },
      { label: "Đêm", value: "TODO — giờ thật" },
    ],
    hoursNote: "Không điền giờ giả. Thay khi quán chốt ca.",
    phoneLabel: "Điện thoại",
    phoneValue: "TODO — số quán",
    zaloLabel: "Zalo",
    zaloValue: "Nhắn từ form (demo)",
    igLabel: "Instagram",
    igValue: "TODO — handle thật",
  },
  faq: {
    eyebrow: "08 / FAQ",
    title: "Trước khi tới",
    items: [
      {
        q: "Có cần đặt bàn không?",
        a: "Nên đặt trước giờ cao điểm và bàn đêm. Form trên demo chỉ minh họa luồng giữ chỗ.",
      },
      {
        q: "Menu trên web có phải món đang bán không?",
        a: "Không. Món là placeholder. Menu vận hành đang ở menu.tamthefnb.com. Site brand kể chuyện; QR để gọi lúc đã ngồi.",
      },
      {
        q: "Có chỗ cho nhóm lớn không?",
        a: "TODO — sức chứa và bàn riêng. Block sự kiện trên demo chưa xác nhận quán nhận tiệc.",
      },
      {
        q: "Thanh toán thế nào?",
        a: "TODO — tiền mặt / chuyển khoản / thẻ. Không bịa cổng thanh toán trên demo.",
      },
    ],
  },
  final: {
    title: "Chọn nhịp,",
    titleEm: "rồi tới.",
    support: "Cà phê, brunch, hay đêm — một địa chỉ trên Minh Khai.",
    ctaPrimary: "Đặt bàn",
    ctaSecondary: "Không gian",
  },
  disclaimer:
    "Demo pitch bởi Dolphin Software. Không phải website chính thức của Tam Thể FNB. Ảnh minh họa lưu local. Giờ, giá, món, SĐT, Instagram: TODO.",
  footer: {
    rights: "Tam Thể · demo",
    by: "Dolphin Software",
  },
  mobileBar: {
    map: "Bản đồ",
    story: "Ba thể",
    book: "Đặt bàn",
  },
} as const;
